version: "3"

services:

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
    cap_add:
      - SYS_PTRACE
      - NET_RAW
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
